### ISSUE TITLE
一直提示不需要openclash

### ISSUE THREAD

**Issue by czjesda** [281677160/autobuild#3]
在编译lede的时候，一直提示不要openclash插件，但是在diy-party.sh又显示有这个插件
# OpenClash
export OpenClash_branch="master"            # OpenClash代码选择分支（master 或 dev）(填0为不需要此插件)
export OpenClash_Core="1"                   # 编译固件增加OpenClash时,把核心下载好,核心为3MB左右大小(1为启用命令,填0为不需要核心)

请问这是什么原因呢？
![1](https://user-images.githubusercontent.com/26915028/222437901-eb5d7652-5122-457b-a19f-bca385150d28.JPG)

**Comment by 281677160** [comment]
不了解，没遇见过这个情况
