### ISSUE TITLE
不知道这个是那个插件导致的问题！

### ISSUE THREAD

**Issue by k3soft912** [281677160/autobuild#6]
g++  -o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/frame-arguments-tq-csa.o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/torque-generated/src/builtins/frame-arguments-tq-csa.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.24"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/generate-bytecode-output-root -I/Ledemaster/openwrt/staging_dir/target-x86_64_musl/usr/include -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/.deps//Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/frame-arguments-tq-csa.o.d.raw   -c
  g++  -o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/function-tq-csa.o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/torque-generated/src/builtins/function-tq-csa.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.24"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/generate-bytecode-output-root -I/Ledemaster/openwrt/staging_dir/target-x86_64_musl/usr/include -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/.deps//Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/function-tq-csa.o.d.raw   -c
  g++  -o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/growable-fixed-array-tq-csa.o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/torque-generated/src/builtins/growable-fixed-array-tq-csa.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.24"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/generate-bytecode-output-root -I/Ledemaster/openwrt/staging_dir/target-x86_64_musl/usr/include -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/.deps//Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/growable-fixed-array-tq-csa.o.d.raw   -c
Error: The operation was canceled.

不知道上面这个错误是那个插件导致的问题！一直编译不出来每次都是超时

**Comment by authon** [comment]
> g++ -o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/frame-arguments-tq-csa.o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/torque-generated/src/builtins/frame-arguments-tq-csa.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.24"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/generate-bytecode-output-root -I/Ledemaster/openwrt/staging_dir/target-x86_64_musl/usr/include -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/.deps//Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/frame-arguments-tq-csa.o.d.raw -c g++ -o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/function-tq-csa.o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/torque-generated/src/builtins/function-tq-csa.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.24"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/generate-bytecode-output-root -I/Ledemaster/openwrt/staging_dir/target-x86_64_musl/usr/include -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/.deps//Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/function-tq-csa.o.d.raw -c g++ -o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/growable-fixed-array-tq-csa.o /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/torque-generated/src/builtins/growable-fixed-array-tq-csa.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_HAVE_TARGET_OS' '-DV8_TARGET_OS_LINUX' '-DV8_EMBEDDER_STRING="-node.24"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ATOMIC_MARKING_STATE' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen -I/Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj/gen/generate-bytecode-output-root -I/Ledemaster/openwrt/staging_dir/target-x86_64_musl/usr/include -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/.deps//Ledemaster/openwrt/build_dir/target-x86_64_musl/node-v16.19.1/out/Release/obj.host/v8_initializers/gen/torque-generated/src/builtins/growable-fixed-array-tq-csa.o.d.raw -c Error: The operation was canceled.
> 
> 不知道上面这个错误是那个插件导致的问题！一直编译不出来每次都是超时

+1
