### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ahfncj** [281677160/autobuild#8]
go: ../../go.mod requires go >= 1.21.4 (running go 1.21.3; GOTOOLCHAIN=local)

Building targets
go: ../../go.mod requires go >= 1.21.4 (running go 1.21.3; GOTOOLCHAIN=local)

make[3]: *** [Makefile:91: /Ledemaster/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/Xray-core-1.8.6/.built] Error 1
make[3]: Leaving directory '/Ledemaster/openwrt/feeds/passwall3/xray-core'
time: package/feeds/passwall3/xray-core/compile#0.12#0.09#0.19
    ERROR: package/feeds/passwall3/xray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall3/xray-core/compile] Error 1
make[2]: Leaving directory '/Ledemaster/openwrt'
make[1]: *** [package/Makefile:110: /Ledemaster/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/Ledemaster/openwrt'
make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by datout** [comment]
> go: ../../go.mod requires go >= 1.21.4 (running go 1.21.3; GOTOOLCHAIN=local)
> 
> Building targets go: ../../go.mod requires go >= 1.21.4 (running go 1.21.3; GOTOOLCHAIN=local)
> 
> make[3]: *** [Makefile:91: /Ledemaster/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/Xray-core-1.8.6/.built] Error 1 make[3]: Leaving directory '/Ledemaster/openwrt/feeds/passwall3/xray-core' time: package/feeds/passwall3/xray-core/compile#0.12#0.09#0.19 ERROR: package/feeds/passwall3/xray-core failed to build. make[2]: *** [package/Makefile:116: package/feeds/passwall3/xray-core/compile] Error 1 make[2]: Leaving directory '/Ledemaster/openwrt' make[1]: *** [package/Makefile:110: /Ledemaster/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/stamp/.package_compile] Error 2 make[1]: Leaving directory '/Ledemaster/openwrt' make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 2 Error: Process completed with exit code 2.

Glong的问题。升级下就好了

**Comment by 281677160** [comment]
golang版本引起的错误，现在应该没问题了，源码作者基本都更新了最新的golang版本
